---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R video_files $DEPLOYPATH
    - /bin/cp -R widgets $DEPLOYPATH 
    - /bin/cp bin-libraries.html $DEPLOYPATH
    - /bin/cp home.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp POST.html $DEPLOYPATH
    - /bin/cp video.html $DEPLOYPATH 